import jsPDF from "jspdf";
import { Invoice } from "@/services/api";

interface InvoiceGeneratorProps {
  invoice: Invoice & { userEmail: string }; // Assume userEmail available
  userName?: string;
  userPhone?: string;
}

export const generateInvoicePDF = ({ invoice, userName = "Member", userPhone = "N/A" }: InvoiceGeneratorProps) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(30, 64, 120);
  doc.rect(0, 0, pageWidth, 40, "F");

  // Logo
  try {
    const img = new Image();
    img.src = new URL("./AGLlogo.png", import.meta.url).href;
    doc.addImage(img, "PNG", 10, 5, 30, 30);
  } catch {
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("AGL", 20, 24);
  }

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", pageWidth - 15, 20, { align: "right" });
  doc.setFontSize(10);
  doc.text(`#INV-${invoice.id.toString().padStart(3, '0')}`, pageWidth - 15, 30, { align: "right" });

  doc.setTextColor(50, 50, 50);

  let y = 55;
  const leftX = 20;
  const rightX = pageWidth - 20;

  // Invoice Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Date:", leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.date, leftX + 45, y);

  y += 12;

  // Member Information
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", leftX, y);
  y += 8;

  doc.setFontSize(10);
  const fields = [
    ["Name", userName],
    ["Email", invoice.userEmail],
    ["Phone", userPhone],
  ];

  fields.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(value || "N/A", leftX + 45, y);
    y += 8;
  });

  y += 8;

  // Invoice Details
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Description", leftX, y);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.description, leftX, y + 6);
  y += 25;

  // Amount
  doc.setFillColor(240, 245, 250);
  doc.roundedRect(leftX, y - 6, pageWidth - 40, 24, 3, 3, "F");
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Amount:", leftX + 8, y + 6);
  doc.setFontSize(16);
  doc.setTextColor(30, 64, 120);
  const amountNum = parseFloat(invoice.amount.replace(/[^0-9.]/g, ''));
  doc.text(`Ksh ${amountNum.toLocaleString()}`, rightX - 8, y + 6, { align: "right" });

  // Status
  y += 35;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Status:", leftX, y);
  doc.setTextColor(invoice.status === 'Paid' ? 0 : 200, 150, 0);
  doc.text(invoice.status, leftX + 35, y);

  // Footer
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.text("This is an official invoice generated by AGL Member Portal.", pageWidth / 2, footerY, { align: "center" });
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, footerY + 8, { align: "center" });

  doc.save(`Invoice_${invoice.id}_AGL.pdf`);
};

